name: rnaseq
channels:
  - conda-forge
  - bioconda
  - r
  - nodefaults
dependencies:
  - pigz
  - python
  - pysam
  - snakemake
  - graphviz
  - salmon
  - fastqc
  - cutadapt
  - bedtools
  - ucsc-bedgraphtobigwig
  - pandoc
  - tbb
  - samtools
  - hisat2
  - stringtie
  - trim-galore
  - multiqc
  - igv
  - igvtools
  - r-base
  - r-tidyverse
  - r-furrr
  - r-devtools
  - r-glue
  - r-patchwork
  - r-ggsci
  - r-tinytex
  - r-curl
  - r-rsqlite
  - r-xml2
  - r-httpuv
  - r-mass
  - r-matrix
  - r-pheatmap
  - r-ggtext
  - r-ggrepel
  - r-flextable
  - r-officer
  - r-dt
  - r-ggVennDiagram
  - r-ggvenn
  - r-ashr
  - r-gprofiler2
  - r-msigdbr
  - r-ggplotify
  - bioconductor-complexheatmap
  - bioconductor-rfastp
  - bioconductor-rsamtools
  - bioconductor-rsubread
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-biocinstaller
  - bioconductor-GenomicRanges
  - bioconductor-genefilter
  - bioconductor-GenomicAlignments
  - bioconductor-apeglm
  - bioconductor-rtracklayer
  - bioconductor-enrichplot
  - bioconductor-pathview
  - bioconductor-biomaRt
  - bioconductor-org.hs.eg.db
  - bioconductor-homo.sapiens
  - bioconductor-BSgenome.Hsapiens.UCSC.hg38
  - bioconductor-TxDb.Hsapiens.UCSC.hg38.knownGene
  - bioconductor-EnsDb.Hsapiens.v86
  - bioconductor-AnnotationHub
  - bioconductor-BUSpaRse
  - bioconductor-clusterProfiler
  - bioconductor-tximport
  - bioconductor-tximportdata